spring:
  cloud:
    config:
      override-system-properties: false

  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}

jms:
  listener:
    acknowledge-mode: session
  pub-sub-domain: false
  workload_queue:
    update: ${WORKLOAD_QUEUE_UPDATE}


token:
  duration: ${TOKEN_DURATION}
  secret-key: ${SECRET_KEY}

outbox:
  publisher:
    delay-ms: 5000



