services:

  postgresql:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    
    volumes:
      - postgres:/data/postgres

    networks:
      - microservices-net

    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
      
    volumes:
      - mongo:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    
    networks:
      - microservices-net

    restart: unless-stopped

  activemq:
    image: islandora/activemq:4
    container_name: activemq
    env_file:
      - .env
    ports:
      - "8161:8161"
      - "61616:61616"

    environment:
      ACTIVEMQ_USER: ${ACTIVEMQ_USER}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      ACTIVEMQ_WEB_ADMIN_NAME: ${ACTIVEMQ_WEB_ADMIN_NAME}
      ACTIVEMQ_WEB_ADMIN_PASSWORD: ${ACTIVEMQ_WEB_ADMIN_PASSWORD}
      ACTIVEMQ_WEB_ADMIN_ROLES: ${ACTIVEMQ_WEB_ADMIN_ROLES}
    volumes:
      - activemq:/opt/activemq/data

    networks:
      - microservices-net

    restart: unless-stopped

  fitness-service:
    build: ./services/fitness-service
    container_name: fitness-service
    env_file:
      - .env
    ports:
      - "8082:8082"

    depends_on:
      - postgresql
      - activemq
      - discovery-server
      - config-server

    volumes:
      - ./logs/fitness:/app/logs
    networks:

      - microservices-net
    restart: unless-stopped
  
  config-server:
    build: ./services/config-server
    container_name: config-server
    env_file:
      - .env
    ports:
      - "8888:8888"

    volumes:
      - ./services/config-server/src/main/resources/configurations:/app/configurations

    depends_on:
      - discovery-server

    networks:
      - microservices-net
    restart: unless-stopped
    
  discovery-server:
    build: ./services/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    
    networks:
      - microservices-net
    restart: unless-stopped

    
  gateaway-server:
    build: ./services/gateaway-server
    container_name: gateaway-server
    ports:
      - "8083:8083"
  
    depends_on:
      - discovery-server
      - config-server
    
    networks:
      - microservices-net
    restart: unless-stopped


  workload-calculator-service:
    build: ./services/workload-calculator-service
    container_name: workload-service
    env_file:
      - .env
    ports:
      - "8080:8080"
  
    depends_on:
      - discovery-server
      - config-server

    volumes:
      - ./logs/workload:/app/logs

    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
  activemq:
