spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: password


eureka:
  client:
    enabled: false

security:
  jwt:
    duration: 86400
    signing-key: fitness-rest-application-dev-secret-key
jms:
  listener:
    acknowledge-mode: session
  pub-sub-domain: false
  workload_queue:
    update: main-a-queue
    